### ISSUE TITLE
Won't install on Ubuntu 20.04

### ISSUE THREAD

**Issue by Roadhog360** [sptls/rogauracore_gui#3]
```
Creating resource file...Done
Compiling...g++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++2a’?
make: *** [makefile:12: all] Error 1
```

I've tried to install both `c++20` and `c++2a` with no luck, after installing them using `apt-get` and attempting to install, I get this same error trying to run the `make` command. The above error attached is the entire error.

**Comment by sptls** [comment]
Remove "-std=c++20" from makefile and run make again. Should work fine

**Comment by Roadhog360** [comment]
Works, ty

**Comment by Roadhog360** [comment]
Will there be an option to change the light bar at the front of ROG laptops or the logo color behind the screen? rogauracore can, but it seems the gui does not have the option to edit these, only the single modes seem to change them.

**Comment by sptls** [comment]
> Will there be an option to change the light bar at the front of ROG laptops or the logo color behind the screen? rogauracore can, but it seems the gui does not have the option to edit these, only the single modes seem to change them.

I was not aware that it was an option. I've made this gui mostly for me and my laptop didn't have any logo on the lid and the led strip around the laptop was connected to keyboard rgb.
I'm not planning on adding that feature atm. Sorry!
